_wandb:
    value:
        cli_version: 0.27.2
        e:
            nkhzs9b9o3cwy6eyoiwfyhwhbhl841io:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1022844989440"
                        used: "755245412352"
                email: noriaki@uni.minerva.edu
                executable: C:\Python312\python.exe
                git:
                    commit: 6f6f11f21cc1f994c45362c4f634aaeb5970eebf
                    remote: https://github.com/Jiyungi/weave-hack.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-dfe40758-ca1d-721f-08cf-2ba9e7c92e58
                host: LAPTOP-IP4A2MRC
                memory:
                    total: "33979854848"
                os: Windows-11-10.0.26200-SP0
                program: -m scripts.run_weave_eval
                python: CPython 3.12.6
                root: C:\Users\Mr. Paul\Downloads\Weights and Biases\weave-hack\ml
                startedAt: "2026-06-07T04:56:59.860348Z"
                writerId: nkhzs9b9o3cwy6eyoiwfyhwhbhl841io
        m: []
        python_version: 3.12.6
        t:
            "3":
                - 2
            "4": 3.12.6
            "5": 0.27.2
            "8":
                - 3
            "10":
                - 20
            "12": 0.27.2
            "13": windows-amd64
