import type { ChangeEvent } from "react";
import { CopilotChat } from "@copilotkit/react-ui";
import { INFERENCE_API_URL } from "../config.js";
import type { UnitOption } from "../frontend/chat.js";

export interface ChatViewProps {
  unitOptions: readonly UnitOption[];
  selectedUnit: UnitOption;
  onSelectUnit: (unit: UnitOption) => void;
}

/**
 * CHAT VIEW (Requirement 17.1).
 *
 * A real `<CopilotChat>` from @copilotkit/react-ui wired to the WeaveSelf
 * CopilotKit runtime. A Unit dropdown picks a Unit (unit_label + adapter_id);
 * the selection is forwarded to the runtime (via the provider headers in App)
 * so sending a message calls the Inference_API with the selected adapter_id and
 * the response is rendered in the chat transcript.
 */
export function ChatView(props: ChatViewProps): JSX.Element {
  const { unitOptions, selectedUnit, onSelectUnit } = props;

  const onChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    const next = unitOptions[event.target.selectedIndex];
    if (next !== undefined) {
      onSelectUnit(next);
    }
  };

  const selectedIndex = unitOptions.findIndex(
    (option) =>
      option.adapterId === selectedUnit.adapterId &&
      option.unitLabel === selectedUnit.unitLabel,
  );

  return (
    <section className="ws-chat" data-view="chat">
      <div className="ws-unit-picker">
        <label htmlFor="ws-unit-select">Unit</label>
        <select
          id="ws-unit-select"
          data-testid="unit-select"
          value={selectedIndex < 0 ? 0 : selectedIndex}
          onChange={onChange}
        >
          {unitOptions.map((option, index) => (
            <option key={`${option.unitLabel}:${option.adapterId ?? "base"}`} value={index}>
              {option.unitLabel}
              {option.adapterId !== null ? ` (${option.adapterId})` : ""}
            </option>
          ))}
        </select>
        <span className="ws-unit-meta">
          adapter_id: <code>{selectedUnit.adapterId ?? "—"}</code> · API:{" "}
          <code>{INFERENCE_API_URL}</code>
        </span>
      </div>

      <div className="ws-chat-window">
        <CopilotChat
          instructions={`You are the WeaveSelf adapter for the "${selectedUnit.unitLabel}" Unit.`}
          labels={{
            title: `WeaveSelf · ${selectedUnit.unitLabel}`,
            initial: `Ask anything. Responses are generated by the Inference_API using ${
              selectedUnit.adapterId ?? "the base model (no adapter)"
            }.`,
            placeholder: "Send a message to the selected Unit…",
          }}
        />
      </div>
    </section>
  );
}
